/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FriendshipSchema extends BaseModel {
  static $columns = ['createdAt', 'friendId', 'id', 'status', 'updatedAt', 'userId'] as const
  $columns = FriendshipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare friendId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class LessonCompletedSchema extends BaseModel {
  static $columns = ['completedAt', 'createdAt', 'id', 'lessonId', 'updatedAt', 'userId'] as const
  $columns = LessonCompletedSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lessonId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class LessonOngoingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lessonId', 'startedAt', 'updatedAt', 'userId'] as const
  $columns = LessonOngoingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lessonId: string
  @column.dateTime()
  declare startedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'bio', 'createdAt', 'currentStreak', 'firstname', 'id', 'lastActivityDate', 'lastname', 'longestStreak', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentStreak: number
  @column()
  declare firstname: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare lastActivityDate: DateTime | null
  @column()
  declare lastname: string | null
  @column()
  declare longestStreak: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
